name: Auto Update M3U
on:
  schedule:
    - cron: '0 */3 * * *' # Every 3 hours automatically
  workflow_dispatch: # Allows manual click to update

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests

    - name: Run Converter Script
      run: python update_m3u.py

    - name: Commit and Push M3U File
      run: |
        git config --global user.name 'Github Bot'
        git config --global user.email 'bot@github.com'
        git add live_playlist.m3u
        git commit -m "Auto Updated Playlist" || exit 0
        git push
