name: Auto Update M3U
on:
  schedule:
    - cron: '0 */3 * * *' # প্রতি ৩ ঘণ্টা পর পর অটো রান হবে
  workflow_dispatch: # ম্যানুয়ালি ক্লিক করে টেস্ট করার জন্য

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Latest Tools
      run: |
        pip install --upgrade pip
        pip install requests
        pip install --upgrade yt-dlp

    - name: Execute Personal Code
      run: python update_m3u.py

    - name: Push Generated Playlist
      run: |
        git config --global user.name 'My Custom Bot'
        git config --global user.email 'mybot@github.com'
        git add live_playlist.m3u
        git commit -m "My Live TV Playlist Updated" || exit 0
        git push
